import type { NextPage } from 'next'
import Head from 'next/head'
import styled from 'styled-components'
import Footer from '../components/Footer'
import Header from '../components/Header'

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Ayuth Mangmesap</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Content></Content>
      <Footer />
    </>
  )
}

const Content = styled.main`
  height: 100%;
`

export default Home
