import { SkipNavContent, SkipNavLink } from '@reach/skip-nav'
import type { NextPage } from 'next'
import Head from 'next/head'
import styled from 'styled-components'
import Footer from '../components/Footer'
import Header from '../components/Header'
import ArticleGrid from 'components/ArticleGrid'
import MainContent from 'components/MainContent/MainContent'
import MaxWidthWrapper from 'components/MaxWidthWrapper/MaxWidthWrapper'
import Paragraph from 'components/Paragraph/Paragraph'

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Ayuth Mangmesap</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <HeroHeadingWrapper>
        <Heading>Hello World</Heading>
        <HandWrapper>
          <Hand role="img" aria-label="Waving hand">
            👋
          </Hand>
        </HandWrapper>
      </HeroHeadingWrapper>
      <MainContent>
        <ArticleGrid />
      </MainContent>
      <Footer />
    </>
  )
}

const HeroHeadingWrapper = styled.div`
  height: 100%;
  width: 100%;
  /* min-height: 650px; */
  /* max-height: 750px; */
  /* min-height: 100%; */
  display: flex;
  align-items: center;
  justify-content: center;
`

const Heading = styled.h1`
  font-size: 4rem;
  color: transparent;
  background-color: rgb(255, 178, 62);
  background-image: linear-gradient(
    268.67deg,
    rgb(255, 255, 255) 3.43%,
    rgb(255, 240, 102) 15.69%,
    rgb(255, 163, 26) 55.54%,
    rgb(255, 0, 115) 99%
  );

  background-clip: text;
  -webkit-background-clip: text;
  color: transparent;
`

const Hand = styled.span``

const HandWrapper = styled.p`
  @keyframes wave {
    from {
      transform: rotate(-10deg);
    }
    to {
      transform: rotate(30deg);
    }
  }
  font-size: 3rem;

  ${Hand} {
    display: inline-block;
    animation: wave 1000ms infinite alternate ease-in-out;
    transform-origin: 75% 80%;
  }
`

const PaperStyleWrapper = styled(MaxWidthWrapper)`
  background-color: #171717;
  color: var(--text-white);
  box-shadow: 0px 6px 12px 3px rgba(0, 0, 0, 0.24);
  padding: 52px 72px;
`

export default Home
